####################
##
##  SMART FRIDGE
##  CONFIG FILE
##
####################

reader:
    id_queue:
        sleep : 1
        size : 100
    product_queue:
        sleep : 1
        size : 100
    test_mode:
        sleep : 2
        infinite : yes
    socket_mode:
        port : 7383
    code_reader:
        device : "/dev/video0"
    logs:
        location : "./sf.log"
database:
    ports:
        internal : 2187
    headers:
        internal : "!#+"
    addresses:
        internal : "127.0.0.1"
    logs:
        location : "./sf.log"
