####################
##
##  SMART FRIDGE
##  CONFIG FILE
##
####################

reader:
    id_queue:
        sleep : 1
        size : 5
    product_queue:
        sleep : 3
        size : 6
    test_mode:
        sleep : 2
        infinite : no
    code_reader:
        device : "/dev/video0"
connections:
    ports:
        internal : 2187
    headers:
        internal : "!#+"
    addresses:
        internal : "127.0.0.1"
