BEGIN;

CREATE TABLE IF NOT EXISTS PRODUCTS_DATA (
    CODE TEXT NOT NULL,
    NAME TEXT NOT NULL,
    QUANTITY INT NOT NULL,
    INGREDIENTS_TEXT TEXT,
    BRANDS TEXT,
    EXPIRATION_DATE TEXT,
    LABELS TEXT,
    ELEMENTS INT,
    TIMESTAMP TEXT NOT NULL,
    PRIMARY KEY (CODE)
);

CREATE TABLE IF NOT EXISTS INGREDIENTS_TAGS (
    PRODUCT_NAME TEXT NOT NULL,
    INGREDIENT_NAME TEXT NOT NULL,
    LANGUAGE TEXT,
    PRIMARY KEY (PRODUCT_NAME, INGREDIENT_NAME, LANGUAGE)
);

CREATE TABLE IF NOT EXISTS ALLERGENS_TAGS (
    PRODUCT_NAME TEXT NOT NULL,
    ALLERGEN_NAME TEXT NOT NULL,
    LANGUAGE TEXT,
    PRIMARY KEY (PRODUCT_NAME, ALLERGEN_NAME, LANGUAGE)
);

CREATE TABLE IF NOT EXISTS ADDITIVES_TAGS (
    PRODUCT_NAME TEXT NOT NULL,
    ADDITIVE_NAME TEXT NOT NULL,
    LANGUAGE TEXT,
    PRIMARY KEY (PRODUCT_NAME, ADDITIVE_NAME, LANGUAGE)
);

END;
